---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7

suites:
  - name: chef-12
    driver:
      require_chef_omnibus: 12
    run_list:
      - recipe[iscsicookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

  - name: chef-13
    driver:
      require_chef_omnibus: 13
    run_list:
      - recipe[iscsicookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
